import mongoose from "mongoose"

const settingsSchema = new mongoose.Schema({
    restaurantName: { type: String, default: "TutaFoods" },
    logo: { type: String, default: "" },
    navbarImage: { type: String, default: "" },
    adminNavbarImage: { type: String, default: "" },
    adminProfileImage: { type: String, default: "" },
    appTitle: { type: String, default: "TUTA APP" },
    appSubtitle: { type: String, default: "Enjoy a Smoother Experience — Download Now" },
    playStoreUrl: { type: String, default: "" },
    appStoreUrl: { type: String, default: "" },
    heroImage: { type: String, default: "" },
    heroTitle: { type: String, default: "Order your favourite food here!" },
    heroSubtitle: { type: String, default: "Choose from a diverse range of delicious dishes created by our expert chefs." },
    deliveryFee: { type: Number, default: 38 },
    deliveryTime: { type: String, default: "30-45 minutes" },
    deliveryRadius: { type: Number, default: 10 },
    maxDeliveryDistance: { type: Number, default: 25 },
    maxDeliveryDistance: { type: Number, default: 25 },
    navLinks: { type: [String], default: ["Home", "Menu", "Mobile-app", "Contact us"] },
    footerAbout: { type: String, default: "We serve delicious food with love." },
    footerCopyright: { type: String, default: "Copyright 2026 © TutaFoods - All Right Reserved." },
    facebookUrl: { type: String, default: "" },
    twitterUrl: { type: String, default: "" },
    linkedinUrl: { type: String, default: "" },
    phone: { type: String, default: "" },
    email: { type: String, default: "" },
    address: { type: String, default: "" },
    razorpayKeyId: { type: String, default: "" },
    razorpayKeySecret: { type: String, default: "" },
    onlinePaymentEnabled: { type: Boolean, default: false },
    emailNotificationsEnabled: { type: Boolean, default: true },
    adminEmailNotificationsEnabled: { type: Boolean, default: true },
    whatsappEnabled: { type: Boolean, default: false },
    twilioAccountSid: { type: String, default: "" },
    twilioAuthToken: { type: String, default: "" },
    twilioWhatsappFrom: { type: String, default: "" },
    adminWhatsappNumber: { type: String, default: "" },
    smsEnabled: { type: Boolean, default: false },
    twilioSmsFrom: { type: String, default: "" },
    adminSmsNumber: { type: String, default: "" },
    websiteUrl: { type: String, default: "" },
    userSiteTitle: { type: String, default: "TutaFoods" },
    adminSiteTitle: { type: String, default: "TutaFoods Admin" },
    userFavicon: { type: String, default: "" },
    adminFavicon: { type: String, default: "" },
    emailUser: { type: String, default: "" },
    emailPass: { type: String, default: "" },
    restaurantLat: { type: Number, default: 17.3850 },
    restaurantLng: { type: Number, default: 78.4867 },
    restaurantMapAddress: { type: String, default: "" }
})

const settingsModel = mongoose.models.settings || mongoose.model("settings", settingsSchema)
export default settingsModel
